print ('Введите первый этап развития человека')
etap1=input()
print ('Введите следующий этап развития человека')
etap2=input()
print ('Введите следующий этап развития человека')
etap3=input()
print ('Введите следующий этап развития человека')
etap4=input()
print ('Введите следующий этап развития человека')
etap5=input()
print ('Введите текущий этап развития человека')
etap6=input()
#print ('Ваши этапы эволюции: ',etap1,etap2,etap3,etap4,etap5,etap6, sep='=>')
# как перед первым значением не ставить знак =>?
print ('Ваш ответ:')
print (etap1,etap2,etap3,etap4,etap5,etap6, sep=' => ')
print()
print ('Правильный ответ:')
print ('Homo habilis','Homo erectus','Homo neanderthalensis','Homo heidelbergensis','Homo sapiens idaltu','Homo sapiens sapiens', sep=' => ')
